sudo: required
services:
  - docker

before_install:
  - docker build -t nagib/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nagib/react-test npm test -- --coverage

after_success:
  - docker build -t n4g1b4t0r/multi-client ./client
  - docker build -t n4g1b4t0r/multi-nginx ./nginx
  - docker build -t n4g1b4t0r/multi-server ./server
  - docker build -t n4g1b4t0r/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push n4g1b4t0r/multi-client
  - docker push n4g1b4t0r/multi-nginx
  - docker push n4g1b4t0r/multi-server
  - docker push n4g1b4t0r/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-646064685974
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY